# Generated by Django 4.1.4 on 2023-08-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_site", "0002_country_state_district"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("number", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("department", models.CharField(max_length=100)),
                ("courses", models.CharField(max_length=100)),
                ("purpose", models.CharField(max_length=20)),
                ("materials_provided", models.CharField(max_length=100)),
            ],
        ),
    ]
